dune/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dune_freelance.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

dune_freelance/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta

class Projects_men(models.Model):
    us_manager = models.ForeignKey(User, on_delete=models.CASCADE, default=None, related_name='user')
    name = models.CharField(max_length=45)
    pay = models.IntegerField()
    men_email = models.EmailField(null=True, blank=True)
    date_start = models.DateField()
    date_finish = models.DateField()
    social_category = models.CharField(max_length=255)
    pay_category = models.CharField(max_length=10)
    stat = models.CharField(max_length=15)
    nums = models.IntegerField()

class spec(models.Model):
    us_cpec = models.OneToOneField(User, on_delete=models.CASCADE)
    tel_number = models.CharField(max_length=255)
    rol = models.CharField(max_length=45)

class connect(models.Model):
    user1 = models.OneToOneField(User, on_delete=models.CASCADE, related_name='connections_as_user1')
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='connections_as_user2')

class Bloger(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    photo_bloger = models.ImageField(upload_to='imag/')
    name_first = models.CharField(max_length=255)
    social_net = models.CharField(max_length=45)
    subs = models.CharField(max_length=45)
    tem = models.CharField(max_length=45)
    url_social_net = models.URLField()

class pay(models.Model):
    bloger = models.ForeignKey(Bloger, on_delete=models.CASCADE)
    summ = models.IntegerField(default=0)


class Applications(models.Model):
    pr = models.ForeignKey(Projects_men, on_delete=models.CASCADE, related_name='pr')
    blog = models.ManyToManyField(Bloger,related_name='blog')
    applicat = models.CharField(max_length=45, default='Отправлено')
    kol = models.IntegerField(default=0)



class Posts(models.Model):
    projects_post = models.OneToOneField(Applications, on_delete=models.CASCADE,related_name='apl_blog_us')
    data_konec = models.DateField(default='2024-12-31')
    format = models.CharField(max_length=500, default='Н/Д')
    work_url = models.URLField()
    kol_p = models.IntegerField(default=0)
    photo = models.ImageField(upload_to='imag/', default='image/vk.svg')
    name_url = models.CharField(max_length=255)

class date_post_start(models.Model):
     date_nach = models.DateField()
     apl_date = models.ForeignKey(Posts, on_delete=models.CASCADE)


class result(models.Model):
    pst = models.OneToOneField(Posts, on_delete=models.CASCADE)
    id_res = models.IntegerField()
    id_off = models.IntegerField()
    name_off = models.CharField(max_length=255)
    status_off = models.CharField(max_length=255)
    date_off = models.DateField()
    summ_off = models.IntegerField()

templates/Applications.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>DUNE</title>
</head>
<body>
<div class="flex_block_projects">
    <div class="left_block_projects">
        <div class="projects_main_logo">
            <img src="{% static 'image/dune_main.svg' %}" class="projects_text">
        </div>
        <div class="button_block_projects">
            <button class="button_on_projects_classic" onclick="location.href='{% url 'blogers_m'%}'"><img src="{% static 'image/blogers.png' %}"><p class="projects_classic_button_text">Блогеры</p></button>
            <button class="button_on_projects_classic" onclick="location.href='{% url 'projects_m'%}'"><img src="{% static 'image/grey_projects.png' %}"><p class="projects_classic_button_text">Проекты</p></button>
            <button class="button_on_projects_classic" onclick="location.href='{% url 'post_m'%}'"><img src="{% static 'image/Posts.png'%}"><p class="projects_classic_button_text">Посты</p></button>
            <button class="button_on_projects_classic" onclick="location.href='{% url 'result'%}'"><img src="{% static 'image/statistics.png'%}"><p class="projects_classic_button_text">Результаты</p></button>
            <button class="button_on_projects_classic" onclick="location.href='{% url 'applic_m'%}'"><img src="{% static 'image/Applications.svg' %}"><p class="projects_classic_button_text">Заявки</p></button>
            <button class="button_on_projects_classic" onclick="location.href='{%url 'profile_manager'%}'"><img src="{% static 'image/yellow_profile_icon.svg' %}"><p class="projects_classic_button_text_yellow">Профиль</p></button>
        </div>
    </div>

    <div class="right_block_projects">
        <div class="overflow_block_applications">
            <div class="grid_block_applications">
                {% for a in aplicat %}
                    <div class="prewiew_application_block">
                        <p class="Applications_projects_text">Проект</p>
                        <div class="display_flex_profile_prewiew">
                            {% if a.pr.nums == 1 or a.pr.nums == 7 %}
                                <img src="{% static 'image/1p.png' %}" class="project_logo">
                            {% elif a.pr.nums == 2 or a.pr.nums == 9 %}
                                <img src="{% static 'image/2p.png' %}" class="project_logo">
                            {% elif a.pr.nums == 3 or a.pr.nums == 6 %}
                                <img src="{% static 'image/3p.png' %}" class="project_logo">
                            {% elif a.pr.nums == 4 or a.pr.nums == 8 %}
                                <img src="{% static 'image/4p.png' %}" class="project_logo">
                            {% elif a.pr.nums == 5 or a.pr.nums == 10 %}
                                <img src="{% static 'image/5p.png' %}" class="project_logo">
                            {% endif %}
                            <div class="status_block">
                                <p class="id">id: {{ a.pr.id }}</p>
                                <p class="project_block_nickname">{{ a.pr.name }}</p>
                                <p class="date">{{ a.pr.date_start }}</p>
                                <p class="date">{{ a.pr.date_finish }}</p>
                            </div>
                        </div>

                        <div>
                            {% for blog in a.blog.all %}
                            <p class="blogers_in_application_text">О блогере</p>
                            <div class="display_flex_profile_prewiew">
                                <button class="profile_prewiew_button" ><img src="{{blog.photo_bloger.url}}" class="project_logo"></button>
                                <div class="status_block">
                                    <p class="id">id: {{ blog.id }}</p>
                                    <p class="project_block_nickname">{{ blog.name_first }}</p>
                                </div>
                            </div>
                             <p class="classic_info_text1">Тематика: <span class="info_text">{{ blog.tem }}</span></p>
                            <p class="classic_info_text1">Подписчиков: <span class="info_text">{{ blog.subs }}</span></p>
                            {% endfor %}
                        </div>
                        <div>
                            <p class="classic_info_text1">Соцсети:
                                {% for blog in a.blog.all %}
                                    {% if blog.social_net == 'Instagram' %}
                                        <img src="{% static 'image/social_logo.svg' %}" class="social_network_logo">
                                    {% elif blog.social_net == 'Telegram' %}
                                        <img src="{% static 'image/telegram.svg' %}" class="social_network_logo">
                                    {% elif blog.social_net == 'VK' %}
                                        <img src="{% static 'image/vk.svg' %}" class="social_network_logo">
                                    {% elif blog.social_net == 'Youtube' %}
                                        <img src="{% static 'image/youtube.svg' %}" class="social_network_logo">
                                    {%elif blog.social_net == 'Tiktok'%}
                                        <img src="{% static 'image/Tiktok.svg'%}" class="social_network_logo">
                                    {%elif blog.social_net == 'Twitch'%}
                                        <img src="{% static 'image/Twitch.svg'%}" class="social_network_logo">
                                    {%endif%}
                                {% endfor %}
                            </p>
                        </div>
                        <form method="post">
                            {% csrf_token %}
                        {% if a.applicat == 'Отправлено' %}
                            <input type="radio" name="status" value="Принята"><p>Принять заявку</p>
                            <input type="radio" name="status" value="Отклонено"><p>Отклонить заявку</p>
                            <button type="submit" class="button_status" name="id_a" value="{{ a.id }}">Отправить</button>
                        {% elif a.applicat == 'Принята' %}
                            <button class="button_status">Принято</button>
                        {% elif a.applicat == 'Отклонено' %}
                            <button class="button_cancel_application">Отклонено</button>
                        {% endif %}
                            </form>
                    </div>
                     {% endfor %}
                </div>
            </div>
        </div>
    </div>

</body>
</html>

templates/admin.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>DUNE</title>
</head>
<body>
{%if messages%}
    {% for message in messages %}
    <div class="error open">
        <button class="esc3" onclick="{delete_error()}"><img src="{% static 'image/cross.svg'%}"></button>
        <p class="error_text">Ошибка</p>
        <p class="error_text_addition">{{message}}</p>
    </div>
    {%endfor%}
{%endif%}
<div class="flex_block_projects">
    <div class="left_block_projects">
        <div class="projects_main_logo">
            <img src="{% static 'image/dune_main.svg' %}" class="projects_text">
        </div>
        <div class="button_block_projects">
            <button class="button_on_projects_classic" onclick="location.href='{% url 'blogers_m' %}'">
                <img src="{% static 'image/blogers.png' %}">
                <p class="projects_classic_button_text">Блогеры</p>
            </button>
            <button class="button_on_projects_classic" onclick="location.href='{% url 'projects_m' %}'">
                <img src="{% static 'image/grey_projects.png' %}">
                <p class="projects_classic_button_text">Проекты</p>
            </button>
            <button class="button_on_projects_classic" onclick="location.href='{% url 'post_m' %}'">
                <img src="{% static 'image/Posts.png' %}">
                <p class="projects_classic_button_text">Посты</p>
            </button>
            <button class="button_on_projects_classic" onclick="location.href='{% url 'result' %}'">
                <img src="{% static 'image/statistics.png' %}">
                <p class="projects_classic_button_text">Результаты</p>
            </button>
            <button class="button_on_projects_classic" onclick="location.href='{% url 'applic_m' %}'">
                <img src="{% static 'image/Applications.svg' %}">
                <p class="projects_classic_button_text">Заявки</p>
            </button>
            <button class="button_on_projects_classic" onclick="location.href='{% url 'profile_manager' %}'">
                <img src="{% static 'image/profile_icon.svg' %}">
                <p class="projects_classic_button_text">Профиль</p>
            </button>
        </div>
    </div>

    <div class="right_block_projects">
        <div class="commands_block">
            <div class="admin_panel_display_flex">
                <button class="admin_panel_change_type" onclick="location.href='{% url 'applic' %}'">Заявки</button>
                <a href="{% url 'applic' %}"><img src="{% static 'image/gap.svg' %}" class="mark_tick_admin_panel"></a>
            </div>
            <div class="admin_panel_display_flex">
                <button class="admin_panel_change_type" onclick="location.href='{% url 'random' %}'">Генерация пароля</button>
                <a href="{% url 'random' %}"><img src="{% static 'image/gap.svg' %}" class="mark_tick_admin_panel"></a>
            </div>
            <div class="admin_panel_display_flex">
                <button class="admin_panel_change_type">База данных/раздача прав доступа</button>
                <a href="{% url 'admin:index' %}" class="btn btn-primary"><img src="{% static 'image/gap.svg' %}" class="mark_tick_admin_panel"></a>
            </div>
            <button class="submit_data2" id="open-add-paying">Добавить оплату блогера</button>
        </div>
    </div>
</div>

<div class="modal_add" id="add-modal-block-paying">
    <div class="modal_box2">
        <button class="esc" id="close-add-paying"><img src="{% static 'image/cross.svg' %}"></button>
        <form method="post">
        <p class="addition_text">Выбрать <span class="yellow_span">блогера</span></p>
        <div class="display_flex_blogger_paying_block">
            {%for up in list%}
            {%csrf_token%}
            <input type="radio" name="id_blog_pay" value="{{ up.upm.id }}">
            <div class="prewiew_project_block">
                <div class="display_flex_profile_prewiew">
                    <button class="profile_prewiew_button" >
                        <img src="{{up.upm.photo_bloger.url}}" class="project_logo">
                    </button>
                    <div class="status_block">
                        <p class="id">id: {{up.upm.id}}</p>
                        <p class="project_block_nickname">{{up.upm.name_first}}</p>
                    </div>
                </div>
                <div class="display_flex_social_text_bloggers">
                    <p class="social_text_bloggers">Подписчики</p>
                </div>
                <div class="display_flex_status_bloggers">
                    <p class="Yellow_projects_text">{{up.upm.subs}}</p>
                </div>
                <p class="bloggers_theme">Тематика: <span class="type_of_theme">{{up.upm.tem}}</span></p>
                <div class="display_flex_social_status_blogers">
                    <p class="social_network_blogers">Соцсеть:</p>
                     {%if up.upm.social_net == 'Instagram'%}
                        <img src="{% static 'image/social_logo.svg'%}" class="social_network_logo">
                    {%elif up.upm.social_net == 'Telegram'%}
                        <img src="{% static 'image/telegram.svg'%}" class="social_network_logo">
                    {%elif up.upm.social_net == 'VK'%}
                        <img src="{% static 'image/vk.svg'%}" class="social_network_logo">
                    {%elif up.upm.social_net == 'Youtube'%}
                        <img src="{% static 'image/youtube.svg'%}" class="social_network_logo">
                    {%endif%}
                </div>
                <div class="display_flex_social_status_blogers">
                    <p class="social_network_blogers">Выплата:{{up.summ}}</p>
                </div>
            </div>
            {%endfor%}
        </div>
        <p class="addition_text">Добавление оплаты <span class="yellow_span">блогера</span></p>
        <input type="number" name="pay_input_project" placeholder="Введите оплату блогера" class="input_bloger_paying">
        <button class="button_submit" type="submit" id="commit-add-paying">Подтвердить</button>
        </form>
    </div>
</div>
<script src="{% static 'js/posts.js'%}"></script>
<script src="{% static 'js/admin_panel.js' %}"></script>
</body>
</html>

templates/auth.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css'%}" >
    <title>DUNE</title>
</head>
<body>

{%if messages%}
    {% for message in messages %}
    <div class="error open">
        <button class="esc3" onclick="{delete_error()}"><img src="{% static 'image/cross.svg'%}"></button>
        <p class="error_text">Ошибка</p>
        <p class="error_text_addition">{{message}}</p>
    </div>
    {%endfor%}
{%endif%}
    <div>
        <img src="{% static 'image/Ellipse 126.png'%}" alt="49" class="register_yellow_background">
    <img src="{% static 'image/coin.png'%}" alt="1" class="sign-coin1">
    <img src="{% static 'image/coin.png'%}" alt="2" class="sign-coin2">
</div>
<div>
    <P class="registration_header_text">УКАЖИТЕ ВАШУ</P>
    <P class="registration_yellow_header_text">ПОЧТУ И ПАРОЛЬ</P>
</div>

<form method="post">
    {%csrf_token%}
    <div>
        <input type="text" class="registration_window" placeholder="Логин" name="login">
        <br>
        <input type="password" class="registration_window" placeholder="Пароль" name="password">
    </div>
    <div class="registration_quation_block">
        <input type="checkbox" class="registration_checkbox" name="remember_me">
        <p class="registration_checkbox_text">Запомнить меня</p>
    </div>

    <div>
        <button class="registration_button">Вход</button>
    </div>
</form>
<div class="registration_quation_block">
        <button onclick="location.href='{% url 'password_reset'%}'" class="registration_password_recovery_button">Забыли пароль?</button>
</div><br>

<div>
    <img src="{% static 'image/coin.png'%}" alt="7" class="sign-coin3">
    <img src="{% static 'image/coin.png'%}" alt="8" class="sign-coin4">
    <img src="{% static 'image/Ellipse 126.png'%}" alt="50" class="register_yellow_background2">
</div>
<script src="{% static 'js/posts.js'%}"></script>
</body>
</html>

templates/password_reset_done.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    <title>DUNE</title>
</head>
<body>
    <div>
        <img src="{% static 'image/Ellipse 126.png'%}" alt="49" class="register_yellow_background">
    <img src="{% static 'image/coin.png'%}" alt="1" class="coin1">
    <img src="{% static 'image/coin.png'%}" alt="2" class="coin2">
</div>
    <div>
      <button class="registration_button">Сообщение отправлено</button>
    </div>


<div>
    <img src="{% static 'image/coin.png'%}" alt="7" class="coin3">
    <img src="{% static 'image/coin.png'%}" alt="8" class="coin4">
    <img src="{% static 'image/Ellipse 126.png'%}" alt="50" class="register_yellow_background2">
</div>
</body>
</html>

templates/posts_m.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>DUNE</title>
</head>
<body>
{%if messages%}
    {% for message in messages %}
    <div class="error open">
        <button class="esc3" onclick="{delete_error()}"><img src="{% static 'image/cross.svg'%}"></button>
        <p class="error_text">Ошибка</p>
        <p class="error_text_addition">{{message}}</p>
    </div>
    {%endfor%}
{%endif%}

    <div class="left_block_projects">
        <div class="projects_main_logo">
            <img src="{% static 'image/dune_main.svg' %}" class="projects_text">
        </div>
<div class="button_block_projects">
    <button class="button_on_projects_classic" onclick="location.href='{% url 'blogers_m'%}'"><img src="{% static 'image/blogers.png'%}"><p class="projects_classic_button_text">Блогеры</p></button>
    <button class="button_on_projects_classic" onclick="location.href='{% url 'projects_m'%}'"><img src="{% static 'image/grey_projects.png'%}"><p class="projects_classic_button_text">Проекты</p></button>
    <button class="button_on_projects_classic" onclick="location.href='{% url 'post_m'%}'"><img src="{% static 'image/yellow_posts.png'%}"><p class="projects_classic_button_text_yellow">Посты</p></button>
    <button class="button_on_projects_classic" onclick="location.href='{% url 'result'%}'"><img src="{% static 'image/statistics.png'%}"><p class="projects_classic_button_text">Результаты</p></button>
    <button class="button_on_projects_classic" onclick="location.href='{% url 'applic_m'%}'"><img src="{% static 'image/Applications.svg' %}"><p class="projects_classic_button_text">Заявки</p></button>
    <button class="button_on_projects_classic" onclick="location.href='{%url 'profile_manager'%}'"><img src="{% static 'image/profile_icon.svg' %}"><p class="projects_classic_button_text">Профиль</p></button>
</div>


    </div>

    <div class="right_block_projects2">
         <div class="filters_block_text">
            <p class="filters_block_text_msg">Тип показываемых постов:</p>
        </div>
        <form method="get">
        <div class="filters_block_buttons">
            <select name="fill_post" class="button_of_filters" onchange="this.form.submit()">
                <option >Выбор</option>
                <option value="my">Мои</option>
                <option value="my_blog">Привязанных блогеров</option>
              </select>
        </div>
        </form>
<div class="left_profile_block">
    <div class="post_block_display_grid">
        {%for ip in apm%}
    <div class="post_block">
        <div class="box_shadows_in_status_block">
            <div class="style_fix7">
        <div class="display_flex_profile_prewiew_info2">
            {%if ip.projects_post.pr.nums == 1 or ip.projects_post.pr.nums == 7%}
                <img src="{% static 'image/1p.png'%}" class="project_logo">
            {%elif ip.projects_post.pr.nums == 2 or ip.projects_post.pr.nums == 9%}
                <img src="{% static 'image/2p.png'%}" class="project_logo">
            {%elif ip.projects_post.pr.nums == 3 or ip.projects_post.pr.nums == 6%}
                <img src="{% static 'image/3p.png'%}" class="project_logo">
            {%elif ip.projects_post.pr.nums == 4 or ip.projects_post.pr.nums == 8%}
                <img src="{% static 'image/4p.png'%}" class="project_logo">
            {%elif ip.projects_post.pr.nums == 5 or ip.projects_post.pr.nums == 10%}
                <img src="{% static 'image/5p.png'%}" class="project_logo">
            {%endif%}
            <div class="status_block">
                <p class="id">id: {{ip.projects_post.pr.id}}</p>
                <p class="project_block_nickname">{{ip.projects_post.pr.name}}</p>
                <p class="date">{{ip.projects_post.pr.date_start}}</p>
                <p class="date">{{ip.projects_post.pr.date_finish}}</p>
            </div>
        </div>
        <p class="status_of_project_in_posts">Статус: <span class="yellow_span">Опубликованный</span></p>
        <form method="post" class="p">
            {%csrf_token%}
            <input type="hidden" value="{{ip.id}}" name="id_apl">
            <label class="label_for_data"><input type="date" name="input_data_post" class="no_vision3"></label>
            <button class="submit_data2">Запланировать пост</button>
        </form>
    </div>
    </div>
    <div class="box_shadow_in_info_text">
        <div class="style_fix5">
        <div class="style_fix">
        <p class="addition_text_info">Информация о <span class="yellow_span">посте</span></p>
        <p class="classic_info_text">Соцсети:
            {% for da_soc in ip.projects_post.pr.social_category %}
                <img src="{% static 'image/'|add:da_soc|add:'.svg'%}" class="social_network_logo">
            {%endfor%}
        </p>
        <p class="classic_info_text">Статус: <span class="info_text">{{ip.projects_post.pr.stat}}</span></p>
        <p class="classic_info_text">Тип оплаты: <span class="info_text">{{ip.projects_post.pr.pay_category}}</span></p>
        <p class="classic_info_text">Оплата: <span class="info_text">{{ip.projects_post.pr.pay}}</span></p>
    </div>
        <p class="manager_info_text">Менеджеры <span class="yellow_span">проекта</span></p>
        <p class="managers_text"> Менеджер 1: <span class="managers_text_info"> {{ip.projects_post.pr.us_manager.email}}</span></p>
        <p class="managers_text"> Менеджер 2: <span class="managers_text_info"> {{ip.projects_post.pr.men_email}}</span></p>
    </div>
    </div>
    <div class="left_posts_block_box_shadows">
        <div class="style_fix2">
            {%for blog in ip.projects_post.blog.all%}
        <div class="style_fix4">
            <p class="addition_text_posts">Информация <span class="yellow_span">о блогере:</span></p>
        <div class="display_flex_profile_prewiew2">
            <button class="profile_prewiew_button" ><img src="{{blog.photo_bloger.url}}" class="profile_logo_bloger"></button>
            <div class="status_block">
                <p class="id">id: {{blog.id}}</p>
                <p class="project_block_nickname">{{blog.name_first}}</p>
                <p class="button_report">
                    {%if blog.social_net == 'Instagram'%}
                        <img src="{% static 'image/social_logo.svg'%}" class="social_network_logo">
                    {%elif blog.social_net == 'Telegram'%}
                        <img src="{% static 'image/telegram.svg'%}" class="social_network_logo">
                    {%elif blog.social_net == 'VK'%}
                        <img src="{% static 'image/vk.svg'%}" class="social_network_logo">
                    {%elif blog.social_net == 'Youtube'%}
                        <img src="{% static 'image/youtube.svg'%}" class="social_network_logo">
                    {%endif%}
                </p>
            </div>
        </div>
        </div>
        <div class="style_fix3">
        <div class="display_flex_social_text_bloggers">
            <p class="social_text_bloggers1">Подписчики</p>
        </div>
        <div class="display_flex_status_bloggers2">
            <p class="Yellow_projects_text">{{blog.subs}}</p>
        </div>
    <button class="redaction_post_button" id="open-add-blogers">Редактировать</button>
    </div>
            {%endfor%}
    </div>
    </div>
    <div class="bloggers_post_info">
        <p class="addition_text_posts">Информация <span class="yellow_span">о посте:</span></p>
        <p class="classic_post_text">Формат: <span class="yellow_span">{{ip.format}}</span></p>
        <p class="classic_post_text">Планируемая дата: <span class="yellow_span">{% for date in ip.date_post_start_set.all %}
                    {{ date.date_nach }}
                {% endfor %}</span></p>
        <p class="classic_post_text">Фактическая дата: <span class="yellow_span">{{ip.data_konec}}</span></p>
        <p class="classic_post_text">Ссылка на пост: <span class="yellow_span"><a href="{{ip.work_url}}">{{ip.work_url}}</a></span></p>
    </div>
    <p class="addition_text_bloger_profile">Статистика <span class="yellow_span">поста</span></p>
<div class="diplay_grid_statistics_block">
    <div class="statistics_underblock">
        <p class="type_of_stat">Проекты</p>
        <p class="count_of_stat">{{ip.kol_p}}</p>
    </div>
    <div class="statistics_underblock">
        <p class="type_of_stat">Посты</p>
        <p class="count_of_stat">{{ip.kol_p}}</p>
    </div>
</div>
<div class="screenshot_block">
    <p class="Yellow_text_for_screen">Скриншоты поста</p>
    <img src="{{ip.photo.url}}" class="screenshot">
</div>
<div class="modal_add" id="add-modal-block-blogers">
        <div class="modal_box">
                <button class="esc" id="close-add-blogers"><img src="{% static 'image/cross.svg'%}"></button>
                <p class="addition_text">Изменение<span class="yellow_span2">поста</span></p>
                <div class="overflow_block_of_modal_box">
                    <form method="post" enctype="multipart/form-data">
                {%csrf_token%}
                    <input type="file" class="no_vision2" name="screenshot_add" id="screenshot_add">
    <label for="screenshot_add"><p class="good_label"> <span class="ssrw">Добавить скриншот</span></p></label>
                      <input type="url" name="url_input_project" placeholder="Введите ссылку на пост" class="input_project_name">
                        <div class="display_flex_date_input">
                        <p class="date_text_modal_box_radius">Реальная:</p>
                        <input type="date" class="input_date" name="finish_project">
                    </div>
                      <div>
                      <p class="Status_in_modal_block_bloggers2">Формат</p>
                      <div class="socials_input_theme">
                          <input type="hidden" name="idd" value="{{ip.id}}">
                        <label><input type="radio" class="checkbox_type" name="format" value="Видео"><span class="Span_label">Видео</span></label>
                        <br>
                        <label><input type="radio" class="checkbox_type" name="format" value="Лайв Видео"><span class="Span_label">Лайв Видео</span></label>
                        <br>
                        <label><input type="radio" class="checkbox_type" name="format" value="Лайв Аудио"><span class="Span_label">Лайв Аудио</span></label>
                        <br>
                        <label><input type="radio" class="checkbox_type" name="format" value="Аудиозапись"><span class="Span_label">Аудиозапись</span></label>
                        <br>
                        <label><input type="radio" class="checkbox_type" name="format" value="Банер"><span class="Span_label">Банер</span></label>
                        <br>
                         <label><input type="radio" class="checkbox_type" name="format" value="Текстовый"><span class="Span_label">Текстовый</span></label>
                        <br>
                        <label><input type="radio" class="checkbox_type" name="format" value="Текстовый графический"><span class="Span_label">Текстовый графический</span></label>
                        <br>
                        </div>
                    </div>
                         <button class="button_submit" type="submit" id="commit-add-blogers">Подтвердить</button>
            </form>
                    </div>


        </div>
    </div>

</div>
{%endfor%}
</div>
</div>
    </div>

    <div class="big_screen" id="big_window">
        <button onclick="{close_screen()}" class="large_button"><img src="{% static 'image/big_plus.svg'%}" class="big_image"></button>
    </div>



    <script src="{% static 'js/posts.js'%}"></script>
</body>
</html>